apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "todoapp.fullname" . }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port }}
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
